My first branch
DannieMo/Portfolio-Website pull request #1
Opened 2021-07-08 13:57 UTC by DannieMo

2021-07-08 14:28 UTC, bellom commented
## Hi @DannieMo  👏  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has been marked as invalid because of the following reasons;
1. PR description is not detailed, kindly list out what you did in this project.
Example; 
![image](https://user-images.githubusercontent.com/31897434/103676409-562b8400-4f81-11eb-80fe-71047649bf62.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

2. README file is not detailed enough.
If check the [Microverse template](https://github.com/microverseinc/readme-template) you will see there is a section where you're supposed to add `Set up`.
So you need to add this project set up so that any non-technical user can set up your app on a local machine.
And also, add a screenshot of your web app.

Example: 
- git clone `your repo`
- cd into the folder
- open `index.html` with live server

3. To make your commit messages look more professional, you should always capitalize them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2021-07-08 18:25 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please add node_modules in .gitignore to clean your project. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-08 18:25 UTC, arslanbisharat commented on README.md
> +(./app_screenshot.png)
- [ ] This link is broken. Please work on it.

2021-07-08 18:25 UTC, arslanbisharat commented on README.md
> +[Live Demo Link](https://livedemo.com)
- [  ] It would be great if you can add live link of the project.

2021-07-08 18:25 UTC, arslanbisharat commented on index.html
> +       <p>Daniel Owiri</p>
- [ ] The logo should be a link enclosed in `a tag`

2021-07-08 18:25 UTC, arslanbisharat commented on index.html
> +    <title>Document</title>
- [ ] [Optional] It would be great if you add a proper title of the prokect here.

2021-07-09 09:27 UTC, AshakaE requested changes
### Hi @DannieMo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 # Required Changes ♻️

- [ ] Please make sure `node_modules` folder is properly ignored from the git track before making a git push and requesting a re-review
_/node_modules_

### Optional suggestions
I suggest you deploy your project with Github pages

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2021-07-09 11:36 UTC, carlos-ssh approved these changes
Hi @DannieMo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-09 11:49 UTC, merged