Added_Middle_Section_of_Project
DannieMo/Portfolio-Website pull request #2
Opened 2021-07-09 19:12 UTC by DannieMo

2021-07-10 00:24 UTC, od-c0d3r requested changes
# Status: Changes Required ♻️

Hi @DannieMo  👋😄, I'm Omar and I will be your reviewer for this project 😊

Good job so far!👌😃

There are some issues that you still need to work on to go to the next project but you are **almost there!** 🏁🏁🏁


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_NONE_

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-10 00:24 UTC, od-c0d3r commented on index.html
> +
Good work, following HTML best practices using HTML semantics 😎 
which will defiantly enhance your SEO ranking. 💹 

_You could add also `<aside>` , `<article>` and `<summery>` to your collection ➕_

2021-07-10 00:24 UTC, od-c0d3r commented on index.html
Congrats on the hard work you put into that project ^^!
Your PR looks so professional with a descriptive message. 💯 😄 

_Area to improve:_
_- Add more one-line descriptive commits._

2021-07-10 00:27 UTC, od-c0d3r commented on index.html
> +                        <button type="button">See Project</button>
Well-made mocked UI design from your Figma Template ^^! 
_Impressive_

There is another requirement needs to be added 🔽 

![fa8b3dff-60a9-4b8b-9d44-6be30387cd53](https://user-images.githubusercontent.com/24830039/125146504-65ed7600-e126-11eb-9c51-57798c31a0a0.png)

2021-07-10 00:34 UTC, od-c0d3r commented on index.html
> +                             <p>Ruby</p>
[Required] Each project technology needs to be nested in the `<ul>` tag and each technology with `<li>` tag. 👍🏼

2021-07-10 12:59 UTC, Emmyn5600 approved these changes
## Status: Approved :heavy_check_mark: :muscle::clap:

Hi @DannieMo 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer. There is nothing else to say other than... it's time to merge it :+1: .
Congratulations! :tada:

### Optional suggestions
- [ ] You need to make more commits or to commit oftentimes instead of pushing your changes at once.

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-10 13:09 UTC, merged

2021-07-12 06:38 UTC, od-c0d3r commented
Well done @DannieMo  😎