Milestone 3: Portfolio Website
DannieMo/Portfolio-Website pull request #3
Opened 2021-07-13 17:50 UTC by DannieMo

2021-07-13 18:05 UTC, Shaher-11 requested changes
#### Hello @DannieMo,

### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:smiley::smiley:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [ ] Check the comments below:point_down:


_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

2021-07-13 18:05 UTC, Shaher-11 commented on index.html
> +            <textarea name="user-message" class="contact-element2" cols="30" rows="10" placeholder="Write your message here"></textarea><br><br>
Add some space between the mail field the message field 
#### Original design
![right](https://user-images.githubusercontent.com/58376020/125502500-719394fd-50db-4a2b-9f9d-60b9a6436125.png)

#### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/125502541-fa23ef94-433c-4c15-897e-0bac02a315a5.png)

2021-07-13 18:05 UTC, Shaher-11 commented on index.html
> +            <button type="button" class="contact-button">Seen</button>
Change the button as shown below
#### Original design
![right](https://user-images.githubusercontent.com/58376020/125502711-b4d27a70-07c7-425b-8e9f-f7297e5752f9.png)

#### Your Project
![wrong](https://user-images.githubusercontent.com/58376020/125502738-e25318f2-daee-4038-96fb-795dee7d24cb.png)

2021-07-13 18:05 UTC, Shaher-11 commented on index.html
> +        <footer class="socials">
Reduce the space between the from the social icons

2021-07-14 04:11 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-14 04:22 UTC, merged