Milestone 4: Portfolio Website
DannieMo/Portfolio-Website pull request #6
Opened 2021-07-22 17:27 UTC by DannieMo

This is the fourth milestone of my portfolio website. In this milestone i:
- I used media queries to make my website respond to the different viewport, e.g desktop, and mobile. 
- Added links to my header elements. When you click, it brings you to that section of the website. You should try it out.😃

PS. This is a practice project at Microverse: a remote software programming school. This project is my personal portfolio showing my work, skills, and history. You can seek me out if you are interested in the things I do or just chatting 😉.

2021-07-22 19:45 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED 🛑🛠**
Hello @DannieMo and @gabrielcoder247 👋🏽
You have done a great job so far 👏🏽. You have almost passed all the checks necessary but there are a few changes to make in order to have your project approved.

## Required Changes ♻️
_Check the comments under the review._ 👇🏽👀

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-22 19:45 UTC, emmanuellekamwa commented on README.md
> -![image]![image](https://user-images.githubusercontent.com/53879944/126331491-61556a3f-bb2b-468f-9e12-d90eb9d1e11c.png)
If I am not mistaken I can see that this image is not displaying itself on your readme. Please you can either fix it or delete it if it is not useful for you guys.

2021-07-22 19:45 UTC, emmanuellekamwa commented on index.html
> +                <button type="submit" class="contact-button">Send message</button>
Please try and stick to the design.
The original design 👇🏽

![Screenshot 2021-07-22 193145](https://user-images.githubusercontent.com/61285247/126692217-801d8a66-4811-4834-be84-69484434a3ff.png)
Your design 👇🏽

![Screenshot 2021-07-22 193054](https://user-images.githubusercontent.com/61285247/126692401-65603e52-e0a2-434e-b261-371ce989e15d.png)
As you can see on the desktop version of the original design the name field is divided into 2 parts but on yours displays what it is supposed to display on mobile view so based on the pictures I have sent you just change the name field and all the placeholders.

2021-07-23 03:20 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-23 08:34 UTC, merged